//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test1.UI_Strings", typeof(UI_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Guides.
        /// </summary>
        internal static string AccessibilityGuides {
            get {
                return ResourceManager.GetString("AccessibilityGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Tools.
        /// </summary>
        internal static string AccessibilityTools {
            get {
                return ResourceManager.GetString("AccessibilityTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have this application!.
        /// </summary>
        internal static string AppAlreadyInstalled {
            get {
                return ResourceManager.GetString("AppAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicaiton will not be shown on the menu until it is reloaded. 
        ///(This application has not been removed from your pendrive.).
        /// </summary>
        internal static string appHidden {
            get {
                return ResourceManager.GetString("appHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not found! 
        ///This application will no longer be shown in the menu..
        /// </summary>
        internal static string AppNotFound {
            get {
                return ResourceManager.GetString("AppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not found! 
        ///This application will not be shown when the menu is next loaded.
        /// </summary>
        internal static string AppNotFoundError {
            get {
                return ResourceManager.GetString("AppNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black on Cream.
        /// </summary>
        internal static string ColourSchemeBonC {
            get {
                return ResourceManager.GetString("ColourSchemeBonC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black on Pink.
        /// </summary>
        internal static string ColourSchemeBonP {
            get {
                return ResourceManager.GetString("ColourSchemeBonP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black on Pale Blue.
        /// </summary>
        internal static string ColourSchemeBonPB {
            get {
                return ResourceManager.GetString("ColourSchemeBonPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black on White.
        /// </summary>
        internal static string ColourSchemeBonW {
            get {
                return ResourceManager.GetString("ColourSchemeBonW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black on Yellow.
        /// </summary>
        internal static string ColourSchemeBonY {
            get {
                return ResourceManager.GetString("ColourSchemeBonY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White on Black.
        /// </summary>
        internal static string ColourSchemeWonB {
            get {
                return ResourceManager.GetString("ColourSchemeWonB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow on Blue.
        /// </summary>
        internal static string ColourSchemeYonB {
            get {
                return ResourceManager.GetString("ColourSchemeYonB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing to this colour would give a poor luminosity ratio and would therefore be difficult to read. 
        ///This has been cancelled to avoid problems..
        /// </summary>
        internal static string ContrastWarning {
            get {
                return ResourceManager.GetString("ContrastWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cream.
        /// </summary>
        internal static string Cream {
            get {
                return ResourceManager.GetString("Cream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create menu - menu.xml not found! 
        ///Try restarting the menu to resolve this problem..
        /// </summary>
        internal static string createMenuError {
            get {
                return ResourceManager.GetString("createMenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        internal static string CustomColour {
            get {
                return ResourceManager.GetString("CustomColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Font.
        /// </summary>
        internal static string DefaultFont {
            get {
                return ResourceManager.GetString("DefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded.
        /// </summary>
        internal static string downloaded {
            get {
                return ResourceManager.GetString("downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an application to download.
        /// </summary>
        internal static string DownloaderLabel {
            get {
                return ResourceManager.GetString("DownloaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Error!.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Access Tools Downloader. 
        ///
        ///Please ensure you read any messages that appear throughout the process of adding new applications, and do not close them until instructed to do so. 
        ///
        ///This will ensure that the downloader works effectively, and will provide you with the necessary information to make using Access Tools the best possible experience. 
        ///
        ///By using the Access Tools Downloader you accept that Access Tools holds no responsibility for any damages or loss caused during the installation of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DownloaderWelcome {
            get {
                return ResourceManager.GetString("DownloaderWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your web browser will begin downloading the file. Select &apos;Run&apos; in the box that appears to begin the download..
        /// </summary>
        internal static string DownloadInstallerInstruction1 {
            get {
                return ResourceManager.GetString("DownloadInstallerInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT - DO NOT CLOSE THIS BOX 
        ///
        ///When the download has completed you may receive a security warning. Allow the file to install. 
        ///
        ///Close this message when the installer begins..
        /// </summary>
        internal static string DownloadInstallerInstruction2 {
            get {
                return ResourceManager.GetString("DownloadInstallerInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tools Installation Wizard.
        /// </summary>
        internal static string DownloadWizard {
            get {
                return ResourceManager.GetString("DownloadWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Access Tools Download Wizard. 
        ///
        ///Please follow the instructions provided to ensure your new application is downloaded correctly. Select OK to begin..
        /// </summary>
        internal static string DownloadWizardIntro {
            get {
                return ResourceManager.GetString("DownloadWizardIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT - DO NOT CLOSE THIS BOX 
        ///
        ///Your web browser will begin downloading the file. Select &apos;Save&apos; in the box that appears to begin the download. 
        ///
        ///The destination has been automatically copied for you, paste this into the text box that asks for the target file name, and the zip file will then download. 
        ///
        ///Only close this message when the download has finished..
        /// </summary>
        internal static string DownloadZipInstructions {
            get {
                return ResourceManager.GetString("DownloadZipInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Description.
        /// </summary>
        internal static string EditDescription {
            get {
                return ResourceManager.GetString("EditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you are connected to the Internet.
        /// </summary>
        internal static string ensureInternet {
            get {
                return ResourceManager.GetString("ensureInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete zip file.
        /// </summary>
        internal static string errorDeleting {
            get {
                return ResourceManager.GetString("errorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process application list.
        /// </summary>
        internal static string errorDownloader {
            get {
                return ResourceManager.GetString("errorDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete the required download. Please ensure that you are connected to the Internet.
        /// </summary>
        internal static string errorDownloading {
            get {
                return ResourceManager.GetString("errorDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate help file.
        /// </summary>
        internal static string errorHelpFile {
            get {
                return ResourceManager.GetString("errorHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add new application.
        /// </summary>
        internal static string errorInstalling {
            get {
                return ResourceManager.GetString("errorInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update description.
        /// </summary>
        internal static string ErrorUpdateDescription {
            get {
                return ResourceManager.GetString("ErrorUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Applications.
        /// </summary>
        internal static string FileDownload {
            get {
                return ResourceManager.GetString("FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FileExit {
            get {
                return ResourceManager.GetString("FileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tools recommends that you check for the latest updates for new software. 
        ///
        ///This can usually be done by selecting the &apos;Help&apos; menu and choosing an option such as &apos;Check for Updates&apos;. 
        ///
        ///Regular updates will ensure that your software receives any required security and bug fixes..
        /// </summary>
        internal static string InformToUpdate {
            get {
                return ResourceManager.GetString("InformToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application Installer should have loaded. Follow the steps in the installer until you reach the &apos;Choose Install Location&apos; box. 
        ///
        ///The installation path will have been copied automatically to your clipboard - Paste this into the Install Location box and then Select Install..
        /// </summary>
        internal static string Install1 {
            get {
                return ResourceManager.GetString("Install1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT 
        ///
        ///Only close this message when the installation process has finished completely!.
        /// </summary>
        internal static string Install2 {
            get {
                return ResourceManager.GetString("Install2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT - DO NOT CLOSE THIS BOX 
        ///
        ///AccessTools could not unzip the downloaded file automatically. 
        ///
        ///A window should have loaded showing a list of folders. Right-click (or use the alternatve keyboard command) on the downloaded zip file and choose to extract the files. 
        ///
        ///You will then be asked to select the Destination Folder - this will have been automatically copied for you, you just need to paste it into text box shown. (In rare cases, the copy may not have worked - copy the following path into the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallZipInstruction1 {
            get {
                return ResourceManager.GetString("InstallZipInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///When the unzip has completed, close this message..
        /// </summary>
        internal static string InstallZipInstruction2 {
            get {
                return ResourceManager.GetString("InstallZipInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background Colour.
        /// </summary>
        internal static string kbBackColour {
            get {
                return ResourceManager.GetString("kbBackColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font.
        /// </summary>
        internal static string kbChangeFont {
            get {
                return ResourceManager.GetString("kbChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close AccessTools.
        /// </summary>
        internal static string kbClose {
            get {
                return ResourceManager.GetString("kbClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Colour Combination.
        /// </summary>
        internal static string kbColourCombo {
            get {
                return ResourceManager.GetString("kbColourCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Text Size.
        /// </summary>
        internal static string kbDecreaseText {
            get {
                return ResourceManager.GetString("kbDecreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Font.
        /// </summary>
        internal static string kbDefaultFont {
            get {
                return ResourceManager.GetString("kbDefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Applications.
        /// </summary>
        internal static string kbDownload {
            get {
                return ResourceManager.GetString("kbDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Help.
        /// </summary>
        internal static string kbHelp {
            get {
                return ResourceManager.GetString("kbHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Text Size.
        /// </summary>
        internal static string kbIncreaseText {
            get {
                return ResourceManager.GetString("kbIncreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Colours and Font.
        /// </summary>
        internal static string kbReset {
            get {
                return ResourceManager.GetString("kbReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Colours.
        /// </summary>
        internal static string kbReverseColours {
            get {
                return ResourceManager.GetString("kbReverseColours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Text Colour.
        /// </summary>
        internal static string kbTextColour {
            get {
                return ResourceManager.GetString("kbTextColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        internal static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching.
        /// </summary>
        internal static string Launching {
            get {
                return ResourceManager.GetString("Launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Blue.
        /// </summary>
        internal static string PaleBlue {
            get {
                return ResourceManager.GetString("PaleBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        internal static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem restoring your settings. The default settings will be used, and a new settings file will be created..
        /// </summary>
        internal static string restoreSettingsError {
            get {
                return ResourceManager.GetString("restoreSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to change the colour so that the background would be the same as the text. 
        ///This has been cancelled to avoid problems..
        /// </summary>
        internal static string SameColourWarning {
            get {
                return ResourceManager.GetString("SameColourWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background.
        /// </summary>
        internal static string SettingsChangeBg {
            get {
                return ResourceManager.GetString("SettingsChangeBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Text Colour.
        /// </summary>
        internal static string SettingsChangeFg {
            get {
                return ResourceManager.GetString("SettingsChangeFg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font.
        /// </summary>
        internal static string SettingsChangeFont {
            get {
                return ResourceManager.GetString("SettingsChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Scheme.
        /// </summary>
        internal static string SettingsColourScheme {
            get {
                return ResourceManager.GetString("SettingsColourScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Colours.
        /// </summary>
        internal static string SettingsReverse {
            get {
                return ResourceManager.GetString("SettingsReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on an app to launch.
        /// </summary>
        internal static string statusDoubleClick {
            get {
                return ResourceManager.GetString("statusDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press CTRL + Z to reset settings.
        /// </summary>
        internal static string statusResestSettings {
            get {
                return ResourceManager.GetString("statusResestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to launch.
        /// </summary>
        internal static string statusToLaunch {
            get {
                return ResourceManager.GetString("statusToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tools is still running and can be accessed through this icon.
        /// </summary>
        internal static string StillRunning {
            get {
                return ResourceManager.GetString("StillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size.
        /// </summary>
        internal static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Menu.
        /// </summary>
        internal static string toolStripExit {
            get {
                return ResourceManager.GetString("toolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Menu.
        /// </summary>
        internal static string toolStripShow {
            get {
                return ResourceManager.GetString("toolStripShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tools is starting. Please Wait....
        /// </summary>
        internal static string trayIconLoading {
            get {
                return ResourceManager.GetString("trayIconLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application menu is still running and can be accessed through this icon.
        /// </summary>
        internal static string trayIconMinimised {
            get {
                return ResourceManager.GetString("trayIconMinimised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tools is populating your menu. Please Wait....
        /// </summary>
        internal static string trayIconPopulating {
            get {
                return ResourceManager.GetString("trayIconPopulating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Folders.
        /// </summary>
        internal static string UsersFolders {
            get {
                return ResourceManager.GetString("UsersFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The menu window is now larger than your screen. Press the CTRL + Z to fix any layout problems..
        /// </summary>
        internal static string WindowSizeWarning {
            get {
                return ResourceManager.GetString("WindowSizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application successfully downloaded and prepared for use. Please restart AccessTools to see it in your menu..
        /// </summary>
        internal static string WizardInstallComplete {
            get {
                return ResourceManager.GetString("WizardInstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
